### ISSUE TITLE
Invalid magic wand with quantified permissions and unframed field access on the LHS can be packaged

### ISSUE THREAD

**Issue by frececroka** [viperproject/silicon#490] opened 2020-04-17 15:46 UTC
This program is deemed correct by the Silicon backend (but not the Carbon backend):

```viper
field f: Ref

predicate p(x: Ref)

method foo()
{
    var x: Ref
    inhale acc(x.f)

    package (forall i: Int :: false ==> p(x.f)) --* false
    assert false
}
```

Clearly, already packaging the wand should fail since the LHS does not imply false.

Making absolutely sure the LHS is self-framing solves the problem:

    package (forall i: Int :: false ==> acc(x.f) && p(x.f)) --* false

Not performing a possibly unframed field access also solves the problem:

    package (forall i: Int :: false ==> p(x)) --* false

Not having a quantifier on the LHS also solves the problem:

    package (false ==> p(x.f)) --* false

**Comment by mschwerhoff** [comment] 2020-04-17 15:50
Duplicate of #338

**Closed by mschwerhoff** 2020-04-17 15:50 UTC
Labels: duplicate
