### ISSUE TITLE
Forall, exists, and ADT function causes unsoundness

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#511] opened 2020-08-03 09:32 UTC
I created the following (somewhat minimised) program while trying to implement a map in silver.

```
domain tup {
  function fst(t: tup): Int
}

function hasKey(m: Seq[tup], k: Int): Bool
ensures exists i: Int :: 0 <= i && i < |m| && fst(m[i]) == k 
    && (forall j: Int :: 0 <= j && j < i ==> fst(m[j]) != k)
{
  |m| > 0
  ? hasKey(m[1..], k)
  : false
}

method test() {
  var m: Seq[tup]
  m := Seq()
  assert !hasKey(m, 2)
  assert false
}
```

 I'm pretty sure the postcondition of `hasKey` is incorrect (I think it should be something like `result == exists ...`), but silicon does not think it is a problem. Instead, reports pass, where I would expect a fail from at least the `assert false`. When I remove the `tup` domain, it still doesn't report the `assert` as failing, but it does say that it cannot prove the postcondition of `hasKeyInt`, which I guess is more desirable than allowing the function to pass:

```
function hasKeyInt(m: Seq[Int], k: Int): Bool
ensures exists i: Int :: 0 <= i && i < |m| && m[i] == k 
    && (forall j: Int :: 0 <= j && j < i ==> m[j] != k)
{
  |m| > 0
  ? hasKeyInt(m[1..], k)
  : false
}

method testInt() {
  var m: Seq[Int]
  m := Seq()
  assert !hasKeyInt(m, 2)
  assert false
}
```

Do I have a wrong understanding about how postconditions on functions are treated, or is this a bug?

**Comment by mschwerhoff** [comment] 2020-08-03 18:14
This is indeed a known bug in Silicon (#369), caused by the function postcondition being available before it has been verified (the postcondition sort of proves itself), and it doesn't help that the problem doesn't always surface (as in your second example).

In case you're wondering why `assert false` holds, consider the following program:

```
function foo(): int
  ensures false
{ 0 }

method test() {
  assert foo() == 0
  assert false
}
```

The function postcondition doesn't hold, and an error will be reported (assuming the bug was fixed), so users are aware that something is wrong with function `foo`. Since that is the case, invoking function `foo` in method `test` will not raise an error, and the subsequent `assert false` will verify.

In your example, function postcondition `exists i: Int :: 0 <= i && i < |m| && m[i] == k` is equivalent to false if `m` is empty (more generally, if `m` doesn't contain `k`) — which is the case in method `testInt`, and also why `assert false` holds.

**Comment by mschwerhoff** [comment] 2020-08-03 18:14
Duplicate of #369

**Closed by mschwerhoff** 2020-08-03 18:14 UTC
