### ISSUE TITLE
Failing assert is skipped if followed by failing assert

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#581] opened 2021-11-12 09:21 UTC
I ran into the following program yesterday:

```javascript
field sent: Seq[Int]
field recvd: Seq[Int]
field p: Bool
field chan: Ref

predicate lockInv(diz: Ref) {
  acc(diz.sent, 1 / 2) 
  && acc(diz.recvd, 1 / 2) 
  && (|diz.sent| == |diz.recvd| + 1 ==> acc(diz.sent, 1 / 4)) 
}

method mkNode() returns (res: Ref)
  ensures acc(res.p, write)
  ensures acc(res.chan, write)
  ensures acc(res.sent, 1 / 2)

method fork(diz: Ref)
  requires acc(diz.p, write)
  requires acc(diz.chan, 1 / 2)
  requires acc(diz.sent, 1 / 4)
  requires diz.p ==> acc(diz.sent, 1 / 4) 
  ensures acc(diz.chan, 1 / 2)
  ensures acc(diz.sent, 1 / 4)
  ensures acc(diz.p, write)
  ensures diz.p ==> acc(diz.sent, 1 / 4) 

method main()
{
  var n0: Ref
  
  n0 := mkNode()
 
  fork(n0)

  inhale acc(lockInv(n0), write)
  unfold acc(lockInv(n0), write)
  
  assert acc(n0.sent, 1 / 1) // Assert A
  assert n0.p // Assert B
} 
```

Of interest in this example are assert A and assert B. When both are present, only B fails. This would indicate that A holds, or at least, I always assumed silicon progresses through the statements in a linear manner, unless goto is involved. But, when I comment  assert B, assert A fails. This is not what I'd expect. Unsure if it's a bug, since it's not like I expect either of the asserts to be true, but it was quite surprising and a bit of a headache to debug, so I thought I'd post it here. Especially since there are no quantifiers this might be doable to debug. This was tested with the master branch of silicon.

**Comment by mschwerhoff** [comment] 2021-11-12 09:29
Looks like it might be a duplicate of #403. Please double-check, if it is.

**Comment by bobismijnnaam** [comment] 2021-11-12 09:42
If I change the third element of `lockInv` to be `expr ==> true`, then assert A fails, so it could be a duplicate of #403. If that's the case, then I guess this will be resolved when silicon implements multiple error reporting?

**Comment by mschwerhoff** [comment] 2021-11-12 09:46
Thank you for checking, I'll close it as a duplicate of #403. 

Regarding future development: no guarantees, but that's at least the plan.

**Closed by mschwerhoff** 2021-11-12 09:46 UTC
